### ISSUE TITLE
PHP Deprecated:  The each() function is deprecated

### ISSUE THREAD

**Issue by tarlepp** [andreas-weber/php-junit-merge#12]
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /home/travis/build/andreas-weber/php-junit-merge/vendor/phpunit/phpunit/src/Util/Getopt.php on line 80

This is PHP 7.2 related, see https://travis-ci.org/andreas-weber/php-junit-merge/jobs/320340938

**Comment by sakharovmaksim** [comment]
Hello! This is phpUnit-file, I think that phpUnit implements support for PHP7.2.

**Comment by tarlepp** [comment]
And that is what I mean. This library is using `"phpunit/phpunit": "4.1.*"` which doesn't have that update yet...

**Comment by sakharovmaksim** [comment]
Fixed in https://github.com/andreas-weber/php-junit-merge/pull/13
Waiting for approve by andreas-weber.

**Comment by andreaskweber** [comment]
Approved your changes and created a new release version:

https://github.com/andreas-weber/php-junit-merge/releases/tag/1.0.6

Thanks to all contributors!
